/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MarkRouteImport } from './routes/mark'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmployeeCalendarRouteImport } from './routes/employee-calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkRoute = MarkRouteImport.update({
  id: '/mark',
  path: '/mark',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCalendarRoute = EmployeeCalendarRouteImport.update({
  id: '/employee-calendar',
  path: '/employee-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employee-calendar': typeof EmployeeCalendarRoute
  '/employees': typeof EmployeesRoute
  '/logs': typeof LogsRoute
  '/mark': typeof MarkRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employee-calendar': typeof EmployeeCalendarRoute
  '/employees': typeof EmployeesRoute
  '/logs': typeof LogsRoute
  '/mark': typeof MarkRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employee-calendar': typeof EmployeeCalendarRoute
  '/employees': typeof EmployeesRoute
  '/logs': typeof LogsRoute
  '/mark': typeof MarkRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employee-calendar'
    | '/employees'
    | '/logs'
    | '/mark'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employee-calendar'
    | '/employees'
    | '/logs'
    | '/mark'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employee-calendar'
    | '/employees'
    | '/logs'
    | '/mark'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmployeeCalendarRoute: typeof EmployeeCalendarRoute
  EmployeesRoute: typeof EmployeesRoute
  LogsRoute: typeof LogsRoute
  MarkRoute: typeof MarkRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mark': {
      id: '/mark'
      path: '/mark'
      fullPath: '/mark'
      preLoaderRoute: typeof MarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-calendar': {
      id: '/employee-calendar'
      path: '/employee-calendar'
      fullPath: '/employee-calendar'
      preLoaderRoute: typeof EmployeeCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmployeeCalendarRoute: EmployeeCalendarRoute,
  EmployeesRoute: EmployeesRoute,
  LogsRoute: LogsRoute,
  MarkRoute: MarkRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
